### ISSUE TITLE
Trying to connect to AWS IoT using MQTT over WebSocket with AWS Signature Version 4 authentication.

### ISSUE THREAD

**Issue by abhigithub911** [aws/aws-iot-device-sdk-java#109]
I am trying to connect to AWS IOT using MQTT over WebSocket with AWS Signature Version 4 authentication.
This is my code for doing that.
```
package de.consol.labs.h2c.examples.client.jetty.IotHelper;

import Exceptions.IotException;
import com.amazonaws.services.iot.client.AWSIotException;
import com.amazonaws.services.iot.client.AWSIotMqttClient;
import com.amazonaws.services.iot.client.AWSIotQos;
import com.amazonaws.services.iot.client.AWSIotTopic;
import com.amazonaws.services.iot.client.sample.sampleUtil.SampleUtil;
import de.consol.labs.h2c.examples.client.jetty.EventTopic.EventTopic;
import com.amazonaws.services.iot.client.sample.sampleUtil.SampleUtil.KeyStorePasswordPair;
import org.apache.commons.lang3.StringUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.json.JSONException;
import org.json.JSONObject;

public class IotHelper {

    private static final Logger logger = LogManager.getLogger(IotHelper.class);
    private static final AWSIotQos QOS = AWSIotQos.QOS0;

    //Hardcoded the values as there is just a single client
    private static final String CLIENT_ENDPOINT = "a17zonhurenvih.iot.us-east-2.amazonaws.com";
    private static final String CLIENT_ID = "thingMtoH1";
    private static final String CERTIFICATE_FILE = "...";
    private static final String PRIVATE_KEY_FILE = "...";
    //topic to which the MtoH service subscribes
    private static final String SUBSCRIBE_TOPIC = "directive";
    //topic to which the MtoH service publishes
    private static final String PUBLISH_TOPIC = "event";



    public static void main(String[] args) throws AWSIotException, InterruptedException {
        AWSIotMqttClient client = connectToIoT(CLIENT_ENDPOINT, CLIENT_ID, CERTIFICATE_FILE, PRIVATE_KEY_FILE);
        EventTopic topic = new EventTopic(SUBSCRIBE_TOPIC, QOS);
        subscribeToIoT(client, topic);

    }

    public static AWSIotMqttClient connectToIoT(final String clientEndpoint, final String clientId, final String certificateFile,
                                                final String privateKeyFile) throws AWSIotException, InterruptedException {

        if (StringUtils.isAnyBlank(clientEndpoint, clientId, certificateFile, privateKeyFile)) {
            logger.debug(String.format("Missing required param to connect IoT MQTT client: %s, %s, %s, %s", clientEndpoint,
                    clientId, certificateFile, privateKeyFile));
            throw new IllegalArgumentException("Missing required param to connect IoT MQTT client");
        }

        final KeyStorePasswordPair pair = SampleUtil.getKeyStorePasswordPair(certificateFile, privateKeyFile);
        AWSIotMqttClient client = new AWSIotMqttClient(clientEndpoint, clientId, "accessId", "secretaccesskey");

        //Cconnects to AWS IoT after client instance gets the required parameters
        /*This class will be in connected state till there is a connection failure because of time expired or if there
        is connection break from AWS IoT's end */
        try {
            client.connect();
        } catch (AWSIotException e) {
            throw new IotException(e);
        }
        logger.info("Connected");
        
        return client;
    }

    //A sample JSON string which is published to the IoT
    /*This is to just demonstrate the structure of the JSON that will be published. When an actual directive comes
    the respective parameters will be passed in a similar JSON. */
    /*{
        "directive": {
        "header": {
            "namespace": "SpeechRecognizer",
                    "name": "StopCapture",
                    "messageId": "{{STRING}}",
                    "dialogRequestId": "{{STRING}}"
        },
        "payload": {
        }
    }
    }*/
    public static void publishToIot(final AWSIotMqttClient client, final String topic, final String message) {
        if (client == null || StringUtils.isAnyBlank(topic, message)) {
            logger.debug(String.format("Missing required param to publish to IoT: %s, %s, %s", client, topic, message));
            throw new IllegalArgumentException("Missing required param to publish to IoT");
        }

        logger.info("Attempting to publish to IoT using message: " + message);
        logger.debug("Attempting to publish to IoT using topic: " + topic);
        try {
            client.publish(topic, QOS, message);
            logger.info("Finished publishing message");
        } catch (AWSIotException ex) {
            throw new IotException(ex);
        }
    }

    public static void subscribeToIoT(final AWSIotMqttClient client, AWSIotTopic topic) {
        if (topic == null || client == null) {
            logger.debug(String.format("Missing required param to subscribe to IoT using topic: %s", topic));
            throw new IllegalArgumentException("Missing required param to subscribe to IoT");
        }

        logger.debug("Attempting to subscribe to IoT using topic: " + topic);
        try {
            client.subscribe(topic);
            logger.info("Finished subscription");
        } catch (AWSIotException ex) {
            throw new IotException(ex);
        }
    }
}
```

But it throws out an error saying:

```.   
Jul 26, 2019 4:13:56 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect upgrade.
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:715)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: WebSocket Response header: Incorrect upgrade.
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:148)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:76)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:63)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701)
	... 7 more

Jul 26, 2019 4:13:56 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Jul 26, 2019 4:13:56 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: thingMtoH1
```

What could be the reason ? @liuszeng @johnrotach @jpeddicord @JonathanHenson
I have done exactly the same for MQTT (over TLS 1.2) with X.509 certificate-based mutual authentication.
It worked for that.

**Comment by bretambrose** [comment]
What version of the SDK are you using?  1.3.2 contained an erroneous reference to a version of the paho mqtt client that isn't compatible with the AWS IoT service.

**Comment by volphy** [comment]
I am receiving the same exception with aws-sdk-iot-device-sdk-java 1.3.7 (latest released version).

Enforcing newer paho client (1.2.5) does not help at all.
