### ISSUE TITLE
java.lang.VerifyError: com/amazonaws/services/iot/client/mqtt/AwsIotMqttConnection

### ISSUE THREAD

**Issue by Snehal-Tembare** [aws/aws-iot-device-sdk-java#11]
I am using this code in my android project for IoT 
AWSIotMqttClient a = new AWSIotMqttClient(clientEndpoint, clientId,          awsAccessKeyId,awsSecretAccessKey);
Below is stackTrace I am getting while running my App on the above line
java.lang.VerifyError: com/amazonaws/services/iot/client/mqtt/AwsIotMqttConnection
                                                                         at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.<init>(AbstractAwsIotClient.java:74)
                                                                         at com.amazonaws.services.iot.client.AWSIotMqttClient.<init>(AWSIotMqttClient.java:156)
                                                                         at com.synerzip.rohitd.CameraSpyActivity.onCreate(CameraSpyActivity.java:207)
                                                                         at android.app.Activity.performCreate(Activity.java:5242)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                                         at dalvik.system.NativeStart.main(Native Method)
Can you help me to solve this issue?

**Comment by fengsongAWS** [comment]
Hi @Snehal-Tembare ,

Thanks for using AWS IoT SDK. The AWS IoT Java SDK does not natively support Android yet.  We have another IoT Android SDK for Android development. You can find examples running for AWS IoT pub/sub here.
[Android Pub/Sub Sample](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub)
Please feel free to post your questions if you have problems running that. 

Thanks,
Fengyi
