### ISSUE TITLE
Couldn't connect with AWS IOT using aws-java-sdk

### ISSUE THREAD

**Issue by VelDeveloper** [aws/aws-iot-device-sdk-java#111]
In my application, I have to create things programmatically. we are using spring-boot. I read the documentation and followed this [link][1] to create things using aws-iot-device-sdk-java.

But no luck, Getting below issues.

pom.xml 

 

    <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-iot-device-sdk-java</artifactId>
                <version>1.3.2</version>
            </dependency>

My service class has below code.

    public void getListOfThings() {
            try {
                AWSIotMqttClient client = new AWSIotMqttClient("767596776232.iot.us-east-2.amazonaws.com","XXX-" + System.currentTimeMillis(),accessKey,secretKey);
                client.connect();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

Exception : 

    org.eclipse.paho.client.mqttv3.MqttException: MqttException
    	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:na]
    	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:715) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:na]
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
    	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_101]
    	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_101]
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_101]
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_101]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
    	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
    Caused by: java.net.UnknownHostException: 767596776232.iot.us-east-2.amazonaws.com
    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_101]
    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_101]
    	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_101]
    	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:80) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:na]
    	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:103) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:na]
    	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:61) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:na]
    	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:na]
    	... 8 common frames omitted
    
    019-08-05 02:55:28.633  INFO 25179 --- [pool-3-thread-1] c.a.s.iot.client.core.AwsIotConnection   : Connection temporarily lost
    2019-08-05 02:55:28.633  INFO 25179 --- [pool-3-thread-1] c.a.s.iot.client.core.AwsIotConnection   : Connection retry cancelled or exceeded maximum retries
    2019-08-05 02:55:28.633  INFO 25179 --- [pool-3-thread-1] c.a.s.i.c.core.AbstractAwsIotClient      : Client connection closed: XXX-1564966453275
    com.amazonaws.services.iot.client.AWSIotException
    	at com.amazonaws.services.iot.client.core.AwsIotCompletion.get(AwsIotCompletion.java:213)
    	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.connect(AbstractAwsIotClient.java:178)
    	at com.amazonaws.services.iot.client.AWSIotMqttClient.connect(AWSIotMqttClient.java:604)
    	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.connect(AbstractAwsIotClient.java:159)
    	at com.amazonaws.services.iot.client.AWSIotMqttClient.connect(AWSIotMqttClient.java:566)
    	at com.aws.sample.aws.controller.SampleAwsIot.getListOfThings(SampleAwsIot.java:20)
    	at com.aws.sample.aws.controller.SimpleController.sayIot(SimpleController.java:51)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
    	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
    	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
    	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849)
    	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760)
    	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
    	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
    	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
    	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
    	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)

There is a problem with client endpoint I assume. **What is the prefix we have to use for client endpoint**? 

Also, I have another doubt. I couldn't find any link to create **Things** using this SDK. **Anybody, could you please share any pointer to create Things using Java or spring-boot in AWS-IOT**? 

I don't want to link things with nay device for now. Just I would like to create things using spring-boot.

  [1]: https://jitpack.io/p/aws/aws-iot-device-sdk-java

**Comment by graebm** [comment]
Unless you created the IoT Thing months ago, your endpoint should have "-ats" in it. Like so:
`767596776232-ats.iot.us-east-2.amazonaws.com`

The endpoint format changed last year. You can learn more about that in [this blog post](https://aws.amazon.com/blogs/iot/aws-iot-core-ats-endpoints/) or the [official docs](https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html#server-authentication)

Does that solve the issue?
