### ISSUE TITLE
AWS IOT Java SDK Samples - not working with AccessKey and AccessKeyID

### ISSUE THREAD

**Issue by akvish** [aws/aws-iot-device-sdk-java#127]
I am getting the following error while trying to run AWS IOT Java SDK samples using AccessKey and AceesKeyID

Jan 06, 2020 3:14:17 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Jan 06, 2020 3:14:17 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: adarsh-abc
Jan 06, 2020 3:14:29 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
Jan 06, 2020 3:14:33 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.io.IOException: Already connected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Already connected
	at java.io.PipedOutputStream.connect(PipedOutputStream.java:100)
	at java.io.PipedInputStream.connect(PipedInputStream.java:188)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.<init>(WebSocketReceiver.java:42)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:78)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	... 1 more

Jan 06, 2020 3:14:33 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Jan 06, 2020 3:14:33 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: adarsh-abc
Jan 06, 2020 3:14:57 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
Jan 06, 2020 3:15:01 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.io.IOException: Already connected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Already connected
	at java.io.PipedOutputStream.connect(PipedOutputStream.java:100)
	at java.io.PipedInputStream.connect(PipedInputStream.java:188)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.<init>(WebSocketReceiver.java:42)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:78)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	... 1 more

Jan 06, 2020 3:15:01 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Jan 06, 2020 3:15:01 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: adarsh-abc
Jan 06, 2020 3:15:31 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
Jan 06, 2020 3:15:35 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.io.IOException: Already connected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Already connected
	at java.io.PipedOutputStream.connect(PipedOutputStream.java:100)
	at java.io.PipedInputStream.connect(PipedInputStream.java:188)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.<init>(WebSocketReceiver.java:42)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:78)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	... 1 more

Jan 06, 2020 3:15:35 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Jan 06, 2020 3:15:35 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection retry cancelled or exceeded maximum retries
Jan 06, 2020 3:15:35 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionClosed
INFO: Client connection closed: adarsh-abc
[WARNING] 
com.amazonaws.services.iot.client.AWSIotException
	at com.amazonaws.services.iot.client.core.AwsIotCompletion.get(AwsIotCompletion.java:213)
	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.connect(AbstractAwsIotClient.java:178)
	at com.amazonaws.services.iot.client.AWSIotMqttClient.connect(AWSIotMqttClient.java:604)
	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.connect(AbstractAwsIotClient.java:159)
	at com.amazonaws.services.iot.client.AWSIotMqttClient.connect(AWSIotMqttClient.java:566)
	at com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample.main(PublishSubscribeSample.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)

Command :
mvn exec:java -pl aws-iot-device-sdk-java-samples -Dexec.mainClass="com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample" -Dexec.args="-clientEndpoint endPoint -clientId adarsh-abc -awsAccessKeyId keyid -awsSecretAccessKey secretKey"

**Comment by justinboswell** [comment]
Do you have multiple instances of this running? I see a bunch of  already connected messages in that log, and you are presumably using the same client ID each time (1 connection per client ID per second is the service limit, it will hang up on you if you connect twice with the same client ID).

**Comment by akvish** [comment]
I think the aws-sdk is designed to retry when the connection fails. I tried with a different client ID. Still having same issue

**Comment by justinboswell** [comment]
I see also that this is a websocket connection. Have you provided the required certs and trust store to connect via websockets (as per [the documentation here](https://docs.aws.amazon.com/iot/latest/developerguide/mqtt-ws.html))?

**Comment by akvish** [comment]
I used IAM credentials to create the connection.
