### ISSUE TITLE
com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure MqttException (0) - java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by kuncao** [aws/aws-iot-device-sdk-java#14]
mvn exec:java -pl aws-iot-device-sdk-java-samples -Dexec.mainClass="com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample" -Dexec.args="-clientEndpoint a3b3bee1v25lqs.iot.us-west-2.amazonaws.com -clientId sdk-java -certificateFile ../caokun.cert.pem -privateKeyFile ../caokun.private.key"
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building aws-iot-device-sdk-java-samples 1.1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ aws-iot-device-sdk-java-samples ---
Dec 19, 2016 8:07:25 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.net.SocketTimeoutException: connect timed out
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
        ... 1 more

Dec 19, 2016 8:07:25 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Dec 19, 2016 8:07:25 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: sdk-java
Dec 19, 2016 8:07:28 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
Dec 19, 2016 8:08:28 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.net.SocketTimeoutException: connect timed out
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
        ... 1 more

Dec 19, 2016 8:08:28 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Dec 19, 2016 8:08:28 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: sdk-java
Dec 19, 2016 8:08:34 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
Dec 19, 2016 8:09:34 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.net.SocketTimeoutException: connect timed out
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
        ... 1 more

Dec 19, 2016 8:09:34 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Dec 19, 2016 8:09:34 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: sdk-java
Dec 19, 2016 8:09:46 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
Dec 19, 2016 8:10:48 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.net.SocketTimeoutException: connect timed out
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
        ... 1 more

Dec 19, 2016 8:10:48 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Dec 19, 2016 8:10:48 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: sdk-java
Dec 19, 2016 8:11:12 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
Dec 19, 2016 8:12:12 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.net.SocketTimeoutException: connect timed out
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
        ... 1 more

Dec 19, 2016 8:12:12 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Dec 19, 2016 8:12:12 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: sdk-java
Dec 19, 2016 8:12:42 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
Dec 19, 2016 8:13:42 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.net.SocketTimeoutException: connect timed out
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
        ... 1 more

Dec 19, 2016 8:13:42 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Dec 19, 2016 8:13:42 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection retry cancelled or exceeded maximum retries
[WARNING] 
Dec 19, 2016 8:13:42 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionClosed
INFO: Client connection closed: sdk-java
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.services.iot.client.AWSIotException
        at com.amazonaws.services.iot.client.core.AwsIotCompletion.get(AwsIotCompletion.java:213)
        at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.connect(AbstractAwsIotClient.java:112)
        at com.amazonaws.services.iot.client.AWSIotMqttClient.connect(AWSIotMqttClient.java:501)
        at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.connect(AbstractAwsIotClient.java:93)
        at com.amazonaws.services.iot.client.AWSIotMqttClient.connect(AWSIotMqttClient.java:463)
        at com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample.main(PublishSubscribeSample.java:137)
        ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:21 min
[INFO] Finished at: 2016-12-19T20:13:42+08:00
[INFO] Final Memory: 17M/193M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (default-cli) on project aws-iot-device-sdk-java-samples: An exception occured while executing the Java class. null: InvocationTargetException: AWSIotException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by kuncao** [comment]
in my AWS IoT consol,there is also a notification:
Dec 19, 2016 8:11:29 PM +0800
Mqtt connection lost. Reconnect. Error code: 7. AMQJS0007E Socket error:undefined.

Anyone can help me ?
thanks a  lot

**Comment by liuszeng** [comment]
Hi @kuncao ,

Thank you very much for using AWS IoT Java SDK!

From the error message you listed, I am assuming you are using the SDK client and IoT Console client at the same time. Can you confirm on the client ids you are using to connect these two clients to AWS IoT? Connecting with the same client id in different MQTT connections is not allowed. The next connection will kick out the first connection.

Thanks,
Liusu

**Comment by kuncao** [comment]
@liuszeng 
Thanks you for Help
java-sdk
mvn parameter
Dexec.args="-**clientEndpoint a3b3bee1v25lqs.iot.us-west-2.amazonaws.com -clientId sdk-java** -certificateFile ../caokun.cert.pem -privateKeyFile ../caokun.private.key"

how to check the clientid in IoT Console?

**Comment by kuncao** [comment]
@liuszeng 
When stop  trying  connect with java sdk.
In IoT Console.
when run test ,the following message appear:
Connecting to Device Gateway......  
Mqtt connection lost. Reconnect.
this message will occur many times

**Comment by kuncao** [comment]
@liuszeng 
http://docs.aws.amazon.com/iot/latest/developerguide/diagnosing-connectivity-issues.html
from above url,it seem to need "Add the AWS IoT CA certificate to your client’s trust store."
Is this done automatically or need to add by manul?
thanks

**Comment by johnrotach** [comment]
Hello @kuncao,

It seems like you are seeing two issues. The first is using the Java SDK, the second is an error received from the AWS IoT Console.

For the first, it looks like you are receiving a socket timeout. Can you confirm you are able to connect to your endpoint outside of using the Java SDK? This can be done by trying to telnet to the endpoint, port 8883: `telnet <ENDPOINT> 8883` where your endpoint is of the form `telnet abcdef.iot.us-east-1.amazonaws.com`. Note, your region in the previous example may differ.

Another test can be done using OpenSSL's TLS client: `openssl s_client -connect <customer endpoint>:8883 -tls1_2 -CAfile <path to Root CA cert> -cert <Path to device cert> -key <Path to device private key>`.

For the second, when does this error appear? Does it appear on first connect? Are you able to consistently connect and then receive this error after a certain amount of time? Is an action required (such as switching pages) required to see the error?

Thank you again for reaching out to us regarding your issues and for using AWS IoT.

John

**Comment by kuncao** [comment]
@johnrotach
Thanks johnrotach.
mvn exec:java -pl aws-iot-device-sdk-java-samples -Dexec.mainClass="com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample" -Dexec.args="-clientEndpoint **a3b3bee1v25lqs.iot.us-west-2.amazonaws.com** -clientId sdk-java -certificateFile ../caokun.cert.pem -privateKeyFile ../caokun.private.key"

so 
szv1000082894:~ # telnet  a3b3bee1v25lqs.iot.us-west-2.amazonaws.com 8883
Trying 52.35.84.144...
telnet: connect to address 52.35.84.144: Connection timed out
Trying 54.148.236.94...
telnet: connect to address 54.148.236.94: Connection timed out
Trying 35.160.47.159...

**Comment by kuncao** [comment]
@liuszeng
when run test ,MQTT client can not connect the device gateway
for information security reason,I can't upload the file to the issue.
I have send the email to  liuszeng@amazon.com.
Please check your email.
You can also share the doc with  johnrotach.
thanks all.

**Comment by kuncao** [comment]
szv1000082894:/home/awskey # openssl s_client -connect a3b3bee1v25lqs.iot.us-west-2.amazonaws.com:443 -servername a3b3bee1v25lqs.iot.us-west-2.amazonaws.com -showcerts | openssl x509 -text -noout
connect: Connection timed out
connect:errno=110
unable to load certificate
4972:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:650:Expecting: TRUSTED CERTIFICATE

**Comment by kuncao** [comment]
my endpoint seem to be ok
Custom endpoint
This is your custom endpoint that allows you to connect to AWS IoT. Each of your Things has a REST API available at this endpoint. This is also an important property to insert when using an MQTT client or the AWS IoT Device SDK.

Status
ACTIVE
Your endpoint is provisioned and ready to use. You can now start to publish and subscribe to topics.

Endpoint
a3b3bee1v25lqs.iot.us-west-2.amazonaws.com

**Comment by johnrotach** [comment]
Hello @kuncao,

From the above output, it looks like you are unable to connect to the endpoint. In contrast, when I run this same command I receive this:

```
$> openssl s_client -connect a3b3bee1v25lqs.iot.us-west-2.amazonaws.com:443 -CAfile /path/to/my/rootCA.pem -cert /path/to/my/cert.pem -key /path/to/my/key.pem
CONNECTED(00000003)
depth=2 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2006 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primary Certification Authority - G5
verify return:1
depth=1 C = US, O = Symantec Corporation, OU = Symantec Trust Network, CN = Symantec Class 3 Secure Server CA - G4
verify return:1
depth=0 C = US, ST = Washington, L = Seattle, O = "Amazon.com, Inc.", CN = *.iot.us-west-2.amazonaws.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=Washington/L=Seattle/O=Amazon.com, Inc./CN=*.iot.us-west-2.amazonaws.com
   i:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
 1 s:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
   i:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
---
Server certificate
-----BEGIN CERTIFICATE-----
...
<cert removed for brevity>
...
-----END CERTIFICATE-----
subject=/C=US/ST=Washington/L=Seattle/O=Amazon.com, Inc./CN=*.iot.us-west-2.amazonaws.com
issuer=/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3390 bytes and written 434 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1482340164
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

Notice the `CONNECTED` statement in my output.

A connection timeout usually points to a networking issue and not an issue with certificates or the AWS IoT service.

What do you receive if you paste the endpoint URL (`https://a3b3bee1v25lqs.iot.us-west-2.amazonaws.com`) into a web browser or attempt to do a request with curl `curl https://a3b3bee1v25lqs.iot.us-west-2.amazonaws.com`? You should receive a `Missing Authentication Token` error rather than a connection timeout.

John

**Comment by kuncao** [comment]
@johnrotach 
When I paste the endpoint URL (https://a3b3bee1v25lqs.iot.us-west-2.amazonaws.com) into a web browser
I recieve  the following output
{"message":"Missing Authentication Token","traceId":"87579c24-deba-7ac5-abcc-2b752987de8d"}

can you help to paste the  output of the command
telnet a3b3bee1v25lqs.iot.us-west-2.amazonaws.com 8883
thanks a lot

**Comment by johnrotach** [comment]
Sure. I see:

```
$> telnet a3b3bee1v25lqs.iot.us-west-2.amazonaws.com 8883
Trying 35.160.47.159...
Connected to dualstack.iotmoonraker-u-elb-1w8qnw1336zq-1186348092.us-west-2.elb.amazonaws.com.
Escape character is '^]'.
^]
telnet> close
Connection closed.
$>
```

What do you receive?

**Comment by kuncao** [comment]
szv1000082894:~ # telnet a3b3bee1v25lqs.iot.us-west-2.amazonaws.com 8883
Trying 52.35.84.144...
telnet: connect to address 52.35.84.144: Connection timed out
Trying 54.148.236.94...
telnet: connect to address 54.148.236.94: Connection timed out
Trying 35.160.47.159...
telnet: connect to address 35.160.47.159: Connection timed out
Trying 2620:108:700f::3694:ec5e...
telnet: connect to address 2620:108:700f::3694:ec5e: Network is unreachable
Trying 2620:108:700f::3423:5490...
telnet: connect to address 2620:108:700f::3423:5490: Network is unreachable
Trying 2620:108:700f::23a0:2f9f...
telnet: connect to address 2620:108:700f::23a0:2f9f: Network is unreachable

**Comment by johnrotach** [comment]
This could be a port blocking issue with port 8883 on your network. Do you receive the same error if you attempt the telnet command on port 443?

e.g. `telnet a3b3bee1v25lqs.iot.us-west-2.amazonaws.com 443`

**Comment by kuncao** [comment]
szv1000082894:~ # telnet a3b3bee1v25lqs.iot.us-west-2.amazonaws.com 443
Trying 54.148.236.94...
telnet: connect to address 54.148.236.94: Connection timed out
Trying 35.160.47.159...
telnet: connect to address 35.160.47.159: Connection timed out
Trying 52.35.84.144...
telnet: connect to address 52.35.84.144: Connection timed out
Trying 2620:108:700f::3423:5490...
telnet: connect to address 2620:108:700f::3423:5490: Network is unreachable
Trying 2620:108:700f::3694:ec5e...
telnet: connect to address 2620:108:700f::3694:ec5e: Network is unreachable
Trying 2620:108:700f::23a0:2f9f...
telnet: connect to address 2620:108:700f::23a0:2f9f: Network is unreachable

**Comment by kuncao** [comment]
https://a3b3bee1v25lqs.iot.us-west-2.amazonaws.com

**Comment by kuncao** [comment]
telnet a3b3bee1v25lqs.iot.us-west-2.amazonaws.com 8883

**Comment by johnrotach** [comment]
Hi @kuncao,

The Missing Authentication Token message is expected. A request to that endpoint needs to be authenticated using [AWS Signature V4](http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html). This is typically handled for you automatically when using the AWS CLI or an AWS SDK but not on a raw curl request such as this. The point of this test was to see if you could successfully make a TCP connection (which you did since you received this message back from AWS).

Given this error (and the lack of a connection in the other cases) It appears that you can successfully establish a connection from your personal computer but not from your server. It appears all network traffic is not making it to that endpoint, regardless of the protocol. This may be a network issue from China. Are you able to access any other AWS services from your server?

John

**Comment by kuncao** [comment]
@johnrotach @liuszeng
Merry Christmas

**Comment by kuncao** [comment]
@johnrotach 
 Are you able to access any other AWS services from your server?
----
At current , not try.
But  I put a small file in my s3 bucket with my chrome browser.

**Comment by smoms** [comment]
Hi,

i am following the tutorial https://github.com/aws/aws-iot-device-sdk-java/blob/master/README.md to connect from Java to IoT through MQTT over WebSocket. I am using the simple main:

    	AWSIotMqttClient client = new AWSIotMqttClient(clientEndpoint, clientId, awsAccessKeyId, awsSecretAccessKey);
			client.connect();

But i get error:
WARNING: Connect request failure
MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect connection header
....

I am using my AWS credential. My user is also admin and i have policy for full access to IoT:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "iot:*",
            "Resource": "*"
        }
    ]
}

can you pls help?
thanks lot.

**Comment by abnerlusung** [comment]
Any updates on this? I have the same problem.

See stacktrace below:
`Unable to connect to server (32103) - java.net.ConnectException: Connection timed out: connect (local port 57998 to addr
ess 0:0:0:0:0:0:0:0, remote port 8883 to address 35.166.74.244 (ec2-35-166-74-244.us-west-2.compute.amazonaws.com))
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:90)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:92)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:676)
        at java.lang.Thread.run(Thread.java:805)
Caused by: java.net.ConnectException: Connection timed out: connect (local port 57998 to address 0:0:0:0:0:0:0:0, remote
 port 8883 to address 35.166.74.244 (ec2-35-166-74-244.us-west-2.compute.amazonaws.com))
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:86)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:173)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:899)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:81)
        ... 3 more`

**Comment by kuncao** [comment]
sorry for late update
my colleague  oversea can telnet  telnet a3b3bee1v25lqs.iot.us-west-2.amazonaws.com 8883
but I can not telnet in China.
May be this is forbidden in China
