### ISSUE TITLE
shadow sample run failed

### ISSUE THREAD

**Issue by jonenet** [aws/aws-iot-device-sdk-java#172]
com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
Connect request failure
java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
Client connection lost: client-id

**Comment by jmklix** [comment]
What permissions policy are you using to try to connect? and have you gotten the pubsub sample working?

If you are being limited the policy you can try changing it to this
``` JSON
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```
when testing and once you get it working limit it to only permissions that you need.
