### ISSUE TITLE
AwsIotMqttConnectionListener : Connect request failure

### ISSUE THREAD

**Issue by ap-northeast-0** [aws/aws-iot-device-sdk-java#176]
I want to publish a message to a topic from an Ec2 instance however I am getting the following error.
My code was working fine and publishing messages but does not when I deployed to Ec2.
I have added a role(AWSIoTFullAccess) to the ec2 instance but still getting this error.

```
c.a.s.i.c.m.AwsIotMqttConnectionListener : Connect request failure

org.eclipse.paho.client.mqttv3.MqttException: MqttException
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:736) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.io.IOException: WebSocket Response header: Incorrect upgrade.
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:162) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:80) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:65) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:722) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar:na]
	... 1 common frames omitted
```

```
com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener.onFailure Connect request failure
	MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect upgrade.
		at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
		at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:736)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: java.io.IOException: WebSocket Response header: Incorrect upgrade.
		at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:162)
		at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:80)
		at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:65)
		at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:722)
		... 1 more

```

**Comment by bretambrose** [comment]
How are you sourcing the credentials used to sign the websocket handshake?

**Comment by ap-northeast-0** [comment]
@bretambrose 
> How are you sourcing the credentials used to sign the websocket handshake?

I am using DefaultAWSCredentialsProviderChain to retrieve aws credentials then pass it to AWSIotMqttClient along with client end point, and client id.

DefaultAWSCredentialsProviderChain credentials = new DefaultAWSCredentialsProviderChain();
AWSIotMqttClient client = new AWSIotMqttClient(CLIENT_END_POINT, CLIENT_ID, 
				credentials.getCredentials().getAWSAccessKeyId(), 
				credentials.getCredentials().getAWSSecretKey());

**Comment by bretambrose** [comment]
I believe IMDS credentials are session based which means they need the session token as well.  They will also expire eventually after which the connection will permanently fail to establish on reconnect.
