### ISSUE TITLE
Experiencing the same issue

### ISSUE THREAD

**Issue by bschupbach** [aws/aws-iot-device-sdk-java#32]
How can this be resolved?

`Aug 14, 2017 11:28:50 AM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.lang.NullPointerException
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:690)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:149)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:74)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:77)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:676)
	... 1 more

Aug 14, 2017 11:28:50 AM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost`

**Comment by fengsongAWS** [comment]
Hi @bschupbach ,
Could you elaborate more of your problems so that we can reproduce the issue? 
What version of paho client you are using and how did you config your IoT policy? Are you using websocket or cert file?

Thanks

**Comment by bschupbach** [comment]
Hello,

You can replicate this by using a java lamda function and the latest version of the IoT hub SDK to send a MQTT message. I had to update my Pom.xml file and override the version of Paho to the previous in order for it to work.

Brian Schupbach 
402-770-0035
Bschupbach@gmail.com

**Comment by liuszeng** [comment]
Hi @bschupbach ,

Can you confirm that with Paho MQTT Java client v1.1.0 as the dependency, the issue has been fixed? Also, what is the IoT hub SDK you are using in this case?

Thanks,
Liusu

**Comment by bschupbach** [comment]
Using the java SDK. I had to revert to 110. 111 does not work

Brian Schupbach 
402-770-0035
Bschupbach@gmail.com

**Comment by liuszeng** [comment]
Hi @bschupbach ,

Thanks for your confirmation. Glad to know that downgrading the Paho version works for you.

Liusu
