### ISSUE TITLE
“Connection permanently closed” caused by too many publishes in progress (32202)

### ISSUE THREAD

**Issue by nick1989Gr** [aws/aws-iot-device-sdk-java#47]
The problem we are experiencing is that the MQTT connection is permanently lost after a successful reconnect. This only happens if we filled the offline message queue while disconnected. 

After deep diving into the software stack I noticed the following. After the internet connection is back the IoT client will correctly try to reconnect and onConnectionSuccess() is called in com.amazonaws.services.iot.client.core.AwsIotConnection.java.
```java
@Override
    public void onConnectionSuccess() {
        LOGGER.info("Connection successfully established");
        connectionStatus = AWSIotConnectionStatus.CONNECTED;
        retryTimes = 0;
        cancelRetry();
        // process offline messages
        try {
            while (subscribeQueue.size() > 0) {
                AWSIotMessage message = subscribeQueue.poll();
                subscribeTopic(message);
            }
            while (unsubscribeQueue.size() > 0) {
                AWSIotMessage message = unsubscribeQueue.poll();
                unsubscribeTopic(message);
            }
            while (publishQueue.size() > 0) {
                AWSIotMessage message = publishQueue.poll();
                publishMessage(message);
            }
        } catch (AWSIotException | AwsIotRetryableException e) {
            // should close the connection if we can't send message when
            // connection is good
            LOGGER.log(Level.WARNING, "Failed to send queued messages, will disconnect", e);
            try {
                closeConnection(null);
            } catch (AWSIotException ie) {
                LOGGER.log(Level.WARNING, "Failed to disconnect", ie);
            }
        }
        client.onConnectionSuccess();
        if (connectCallback != null) {
            connectCallback.onSuccess();
            connectCallback = null;
        }
    }
```
In that callback it will try to loop on the messages stored in the publishQueue and send them. These are the messages that were tried to be send during the no internet connection period. If we get an exception during that phase, the catch section will be executed and closeConnection(null) will be called. That will consequently close the MQTT connection. The exception that causes the catch section to execute is: "too many publishes in progress (32202)"

At some point the callback onSucess() from AwsIotMqttConnectionListener.java will be called and since the MQTT connection is closed it will call client.getConnection().onConnectionClosed() which is implemented in com.amazonaws.services.iot.client.core. onConnectionClosed. 
onConnectionClosed will permanently close the aws iot connection.

If I understand correctly what is happening is that the actual in flight messages in Paho are more than the maxInFlight messages. That is caused when AWS tries to send all the messages stored in the offline queue (publishQueue) asynchronously, without any delay. Since we cannot change the MqttOptions from AWS I have no control over the maxInFlight variable. 

Do you have any solution for this problem? 

maxOfflineMqttQueueSize: 64 (default value)
maxInflight: 10 (default value)

**Comment by stevesample** [comment]
Being able to set the maxInFlight value as suggested here: https://github.com/aws/aws-iot-device-sdk-java/issues/42 would likely fix this issue.

**Comment by chaurah** [comment]
Hi @nick1989Gr,
         @stevesample has the best solution. I have added this as a +1 to the issue in our internal tracker.  I will have an internal discussion with the team and try to get this fix included in the next release of the SDK. Apologies for the delayed response.

Please do let us know if you have further questions. Thank you for using AWS IoT.

Rahul

**Comment by nick1989Gr** [comment]
Hi @chaurah 
Thanks for your response. If the best solution is to be able to configure maxInFlight I foresee further issues. We have cases for which we need to have an offline buffer of 10000 messages. The problem here is that i cannot set the maxInFlight to any value because the AWS IoT broker has a limitiation for the inflight messages. 

"Maximum inbound unacknowledged messages: The message broker allows 100 in-progress unacknowledged messages per client. (This limit is applied across all messages that require ACK.) When this limit is reached, no new messages are accepted from this client until an ACK is returned by the server. " [source](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot)

**Comment by fengsongAWS** [comment]
Hi @nick1989Gr ,
Which version of Paho you are using right now? I am trying to reproduce your problem. Right now, I can see that the max offline messages cannot exceed 64. Once it is back online, Paho is able to handle all those messages and published them all. Could you elaborate on your case?

**Comment by nick1989Gr** [comment]
Hi @fengsongAWS, 

Currently we are using the latest version of AWS IoT Java SDK 1.1.1. The AWS java SDK has the following dependency on Paho: 
` sad`

**Comment by nick1989Gr** [comment]
Hi @fengsongAWS,

Currently we are using the latest version of AWS IoT Java SDK 1.1.1. The AWS java SDK has the following dependency on Paho:
```
<dependency>
      <groupId>org.eclipse.paho</groupId>
      <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
      <version>[1.1.0]</version>
</dependency>
```
AWSIotMqttClient.setMaxOfflineQueueSize() allows you to set the maximum offline queue size. 

In order to reproduce this issue fast, try to publish multiple messages at a fast pace. I reproduce it by sending 10 mqtt messages per second. At some point disconnect from the internet and wait for a minute until your offlineQueue is full. While your offlineQueue is not full you get this kind of exceptions: 

```
com.amazonaws.services.iot.client.AWSIotException: com.amazonaws.services.iot.client.core.AwsIotRetryableException: Client is not connected (32104)
	at com.amazonaws.services.iot.client.core.AwsIotConnection.publish(AwsIotConnection.java:232) ~[aws-iot-device-sdk-java-1.1.1.jar:?]
	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.publish(AbstractAwsIotClient.java:186) ~[aws-iot-device-sdk-java-1.1.1.jar:?]
	at com.amazonaws.services.iot.client.AWSIotMqttClient.publish(AWSIotMqttClient.java:793) ~[aws-iot-device-sdk-java-1.1.1.jar:?]
	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.publish(AbstractAwsIotClient.java:181) ~[aws-iot-device-sdk-java-1.1.1.jar:?]
	at com.amazonaws.services.iot.client.AWSIotMqttClient.publish(AWSIotMqttClient.java:768) ~[aws-iot-device-sdk-java-1.1.1.jar:?]
	......
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: com.amazonaws.services.iot.client.core.AwsIotRetryableException: Client is not connected (32104)
	at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnection.publishMessage(AwsIotMqttConnection.java:91) ~[aws-iot-device-sdk-java-1.1.1.jar:?]
	at com.amazonaws.services.iot.client.core.AwsIotConnection.publish(AwsIotConnection.java:226) ~[aws-iot-device-sdk-java-1.1.1.jar:?]
	... 22 more
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Client is not connected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:166) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1027) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnection.publishMessage(AwsIotMqttConnection.java:88) ~[aws-iot-device-sdk-java-1.1.1.jar:?]
	at com.amazonaws.services.iot.client.core.AwsIotConnection.publish(AwsIotConnection.java:226) ~[aws-iot-device-sdk-java-1.1.1.jar:?]
	... 22 more
```


After the offlineQueue is filled and you connect back you will get something like this: 

```
14:33:42.940 WARN  com.amazonaws.services.iot.client.core.AwsIotConnection - Failed to send queued messages, will disconnect
com.amazonaws.services.iot.client.AWSIotException: Too many publishes in progress (32202)
	at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnection.publishMessage(AwsIotMqttConnection.java:93) ~[aws-iot-device-sdk-java-1.1.1.jar:?]
	at com.amazonaws.services.iot.client.core.AwsIotConnection.onConnectionSuccess(AwsIotConnection.java:388) [aws-iot-device-sdk-java-1.1.1.jar:?]
	at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener$1.run(AwsIotMqttConnectionListener.java:52) [aws-iot-device-sdk-java-1.1.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Too many publishes in progress
	at org.eclipse.paho.client.mqttv3.internal.ClientState.send(ClientState.java:496) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.internalSend(ClientComms.java:132) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:156) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1027) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnection.publishMessage(AwsIotMqttConnection.java:88) ~[aws-iot-device-sdk-java-1.1.1.jar:?]
	... 9 more
14:33:42.943 INFO  com.amazonaws.services.iot.client.core.AbstractAwsIotClient - Client connection active: mock
14:33:42.943 INFO  com.ph.sesame.client.IoTClient - publishing: {***somehting***} on topic mock/soundlevel
14:33:42.943 INFO  com.ph.sesame.client.IoTClient - publishing: {***somehting***} on topic mock/soundlevel/threshold
14:33:42.947 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.948 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.948 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.948 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.949 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.949 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.949 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.949 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.949 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.949 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.949 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.949 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.949 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel/threshold: Client is currently disconnecting (32102)
14:33:42.949 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/netinfo: Client is currently disconnecting (32102)
14:33:42.950 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.950 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.950 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.950 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel/threshold: Client is currently disconnecting (32102)
14:33:42.950 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.950 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.950 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundincident: Client is currently disconnecting (32102)
14:33:42.950 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/location: Client is currently disconnecting (32102)
14:33:42.950 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.950 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/locationaccuracy: Client is currently disconnecting (32102)
14:33:42.953 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.953 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/altitude: Client is currently disconnecting (32102)
14:33:42.953 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel/threshold: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic $aws/things/mock/shadow/delete/rejected: Client is currently disconnecting (32102)
14:33:42.954 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.955 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.956 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic $aws/things/mock/shadow/delete/accepted: Client is currently disconnecting (32102)
14:33:42.956 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic $aws/things/mock/shadow/update/rejected: Client is currently disconnecting (32102)
14:33:42.956 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.956 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic $aws/things/mock/shadow/update/accepted: Client is currently disconnecting (32102)
14:33:42.956 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic $aws/things/mock/shadow/get/rejected: Client is currently disconnecting (32102)
14:33:42.956 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.956 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic $aws/things/mock/shadow/get/accepted: Client is currently disconnecting (32102)
14:33:42.956 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.957 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic $aws/things/mock/shadow/update/delta: Client is currently disconnecting (32102)
14:33:42.957 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.957 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.957 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.958 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.964 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.964 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel/threshold: Client is currently disconnecting (32102)
14:33:42.964 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.964 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.964 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel/threshold: Client is currently disconnecting (32102)
14:33:42.965 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.965 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.965 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.965 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.965 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.965 WARN  com.amazonaws.services.iot.client.mqtt.AwsIotMqttMessageListener - Request failed for topic mock/soundlevel: Client is currently disconnecting (32102)
14:33:42.966 INFO  com.amazonaws.services.iot.client.core.AwsIotConnection - Connection permanently closed
14:33:42.966 INFO  com.amazonaws.services.iot.client.core.AbstractAwsIotClient - Client connection closed: mock
```

Please notice that even for 10messages per second you might have to try it a couple of times before you can reproduce it. Maybe putting some breakpoints on the critical spots that I mentioned in my first spot might help. I had to try it at least 10 times before I was able to reproduce it. Thanks for your efforts :)

**Comment by fengsongAWS** [comment]
Are you using QoS 0 or QoS 1? Those limit only applies QoS 1 publish, subscribe, unsubscribe, connect when client requires ACK from server side. 
Do you require All QoS 1 for the offline 10000 messages? If so, this would require Paho not dumping all the messages not fast for the purpose of cloud side processing. Or you can reach to technical support to increase your IoT account level limit. 
If you use QoS 0, as specified in the definition, the messages are at their best effort and arrival is not guaranteed. 

I think in your case, increase maximum inflight queue might be the best effort to tackle down the use case for now and see if Paho handles that well for you.

**Comment by nick1989Gr** [comment]
Hi @fengsongAWS 
Thanks for your answer. We are using QoS1. I am a bit confused here. 
- Which limits are you referring to? My understanding is that even for an offlineQueue size of 64 under the conditions I described before, the client gets disconnected permanently when it should not. I believe this is not a limitation. 
- We indeed need to have QoS 1 for all the 10000 messages. The issue here is that right now I am having a problem with an offlineQueue of 64 messages. The SDK is not working as I would expect. This is not a cloud side processing issue. If this issue is resolved then I guess you are right that we will have to increase the IoT account level limit. 

Indeed I agree that increasing the maximum inflight queue would be the best solution. However, I can't do that since AWS IoT Java SDK does not expose the MqttOptions.

**Comment by fengsongAWS** [comment]
1. There are two limits here. One is offlineQueue size default as 64. The other is cloudside which you have further concerns. Let's not worry about server side limit for now.

2. Right now the SDK does not expose MQTT connect options. We will be working further on this. At the same time, you could extend AwsIotMqttConnection class and build up your own connect options where you can set offlineQueue size. https://github.com/aws/aws-iot-device-sdk-java/blob/c8765af14044cd4e1e537f7b4ce78b9482f47327/aws-iot-device-sdk-java/src/main/java/com/amazonaws/services/iot/client/mqtt/AwsIotMqttConnection.java

Thanks

**Comment by liuszeng** [comment]
Customer has reached out through internal channels. Closing.
