### ISSUE TITLE
Make the AWSIotMqttClient with WebSocket working behind a proxy

### ISSUE THREAD

**Issue by zmcode** [aws/aws-iot-device-sdk-java#49]
Hi everyone,
is there a way to make the AWSIotMqttClient with WebSocket working behind a proxy?

The client is behind an HTTPS proxy and the settings are passed to the application through the http.proxyHost and http.proxyPort JVM options.  

The problem we are facing right now is that the client is unable to resolve the AWS Iot Endpoint, receiving an `UnknownHostException`. Is there a way to solve this issue without local access to a DNS?

**Comment by fengsongAWS** [comment]
Java SDK websocket performs SigV4 authorization and authentication. So, that really depends on how your HTTPS proxy setup, if the proxy just forward from one socket to another. Ideally, it should work. Here is some reference from AWS IoT C++ SDK https://github.com/aws/aws-iot-device-sdk-cpp/pull/9 and the proxy guide http://www.squid-cache.org/ you can look into.

**Comment by zmcode** [comment]
Unfortunately we do not have control over the proxy setup. 
The thing is that if we try with wget or curl it is able to reach the AWS endpoint whereas the AWSIotMqttClient created with IAM credentials is unable to resolve the hostname.

**Comment by fengsongAWS** [comment]
Hi @zmcode ,
We currently do not fully test the SDK with proxy server. The principle is that the AWS uses mutual auth to establish the connection. Both the client and server need to verify each other through root-CA and certificate.

**Comment by zmcode** [comment]
Hi @fengsongAWS,
after a bit of trial and error together we the people managing the network, we managed to reach the aws endpoint going through a SOCKS proxy. 

However we are now facing the following error during the SSL handshake:
```
MqttException (0) - javax.net.ssl.SSLException: java.lang.NullPointerException
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: java.lang.NullPointerException
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1917)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1874)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1857)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1378)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:93)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:75)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
        ... 1 more
Caused by: java.lang.NullPointerException
        at sun.security.ssl.SSLSocketImpl.getHost(SSLSocketImpl.java:2132)
        at sun.security.ssl.Handshaker.getHostSE(Handshaker.java:318)
        at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1154)
        at sun.security.ssl.Handshaker.kickstart(Handshaker.java:960)
        at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1455)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1319)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
        ... 5 more
```
Do you have any suggestion about why this could happen?
Thank you :)

**Comment by AndrewJudson** [comment]
This is also an issue for us. For other AWS clients (e.g. S3 encryption client) we set a ClientConfiguration with our proxy values ala here: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setProxyPassword-java.lang.String-
I'm not sure how to do that here.
