### ISSUE TITLE
Feb 01, 2018 4:03:11 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure WARNING: Connect request failure MqttException (0) - java.lang.NullPointerException         at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)

### ISSUE THREAD

**Issue by bhaskarmr** [aws/aws-iot-device-sdk-java#51]
Hi All,
Since mqtt ports are blocked in my org I am trying to use websockets. I tested it with telnet and it is works fine.
I am able to run the same application with websockets from my laptop and it works fine but when i try to run from raspberry pi i am getting the following error.
I tried to change versions of paho mqtt lib and aws sdks but no use.
the following lib versions used.

aws-iot-device-sdk-java-1.1.0
org.eclipse.paho.client.mqttv3-1.1.0

trying to connect to AWS IOT
Feb 01, 2018 4:03:11 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.lang.NullPointerException
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:133)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:74)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:77)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
        ... 1 more

Feb 01, 2018 4:03:11 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Feb 01, 2018 4:03:11 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: TrackAndTraceClientId
Feb 01, 2018 4:03:14 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
Feb 01, 2018 4:03:17 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.lang.NullPointerException
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:133)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:74)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:77)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
        ... 1 more

Feb 01, 2018 4:03:17 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Feb 01, 2018 4:03:17 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: TrackAndTraceClientId

**Comment by fengsongAWS** [comment]
Hi @bhaskarmr ,
This is a websocket handshake failure thrown by paho and the exception is hot handled properly in version 1.1.0. 
I would suggest double check if you are using the correct IAM credentials and log into cloudwatch to see what is the server side log. 

Thanks,
Fengyi

**Comment by bhaskarmr** [comment]
HI Fengyi,
Thanks for the response, I will check but surprisingly it works on laptop but not on pi.

**Comment by liuszeng** [comment]
Closing due to inactivity.
