### ISSUE TITLE
Client does not recognize network connection disruptions

### ISSUE THREAD

**Issue by innodron** [aws/aws-iot-device-sdk-java#56]
AWSIotMqttClient does not acknowledge the client network connectivity has been disrupted, even if Paho recognizes the timeout.

Below, I have a scheduled task to check connection status and reestablish as necessary. Unfortunately, awsClient.getConnectionStatus() continues to return AWSIotConnectionStatus.CONNECTED even when the WiFi is off. Hence the client cannot recover after WiFi is back on.

I would appreciate any help how to do this properly, if the SDK behavior is intentional.

The code;
```
@FXML
public void initialize() {
    <code skipped ...>
    awsClient = new MyAWSIotMqttClient(AWSHOST, AWSCLIENTID, AWSCLIENTKEY, AWSCLIENTSECRET);
    mqttConnectTask = new Timer();
    mqttConnectTask.schedule(new TimerTask() {
        @Override
        public void run() {
            System.out.println("\n(I) >>> " + System.currentTimeMillis() / 1000 + ": Scheduled AWS connection checker");
            System.out.println(awsClient.getConnectionStatus());
            if (awsClient.getConnectionStatus() != AWSIotConnectionStatus.CONNECTED) {
                System.out.println("\n(I) >>> " + System.currentTimeMillis() / 1000 + ": attempting to reconnect to AWS...");
                mqttConnect();
            }
        }
    }, 0, 15000);
}

void mqttConnect() {
    Task<Void> task = new Task<Void>() {
        @Override
        protected Void call() throws Exception {
            try {
                awsClient.connect();
                if (awsClient.getConnectionStatus() == AWSIotConnectionStatus.CONNECTED)
                    updateProgress(1L, 1L);

                awsClient.subscribe(new TopicListener(AWSSHADOWGETACCEPT, true), true);
                awsClient.subscribe(new TopicListener(AWSSHADOWUPDACCEPT, true), true);

                System.out.println("\n(I) >>> " + System.currentTimeMillis() / 1000 + ": Sending shadow get request...");
                awsClient.publish(new IotMessage(AWSSHADOWGET, AWSIotQos.QOS0, ""));
            } 
            catch (AWSIotException e) {
                e.printStackTrace();
            }
            return null;
        }
    };
    task.progressProperty().addListener((observable, oldValue, newValue) ->  {
        if ( newValue.longValue() == 1L) {
            fLedAwsConnIndicator.setLedColor(Color.GREEN);
            fLedAwsConnIndicator.setOn(true);				
        }
    });
    new Thread(task).start();
}

```

The output:
```

(I) >>> 1520919481: Scheduled AWS connection checker
DISCONNECTED

(I) >>> 1520919481: attempting to reconnect to AWS...
Mar 13, 2018 8:38:03 AM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionSuccess
INFO: Connection successfully established

Mar 13, 2018 8:38:03 AM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionSuccess
INFO: Client connection active: demouser

(I) >>> 1520919484: Sending shadow get request...

(I) <<< 1520919484: Message arrived
[$aws/things/<name skipped>/shadow/get/accepted]
{"state":{"reported":{"connected" <rest skipped ...>

(I) >>> 1520919496: Scheduled AWS connection checker
CONNECTED

*****  Turned WIFI OFF at this point

(I) >>> 1520919511: Scheduled AWS connection checker
CONNECTED

(I) >>> 1520919526: Scheduled AWS connection checker
CONNECTED

(I) >>> 1520919541: Scheduled AWS connection checker
CONNECTED

Mar 13, 2018 8:39:04 AM org.eclipse.paho.client.mqttv3.internal.ClientState checkForActivity
SEVERE: demouser: Timed out as no activity, keepAlive=30,000 lastOutboundActivity=1,520,919,514,095 lastInboundActivity=1,520,919,484,319 time=1,520,919,544,101 lastPing=1,520,919,514,095

(I) >>> 1520919556: Scheduled AWS connection checker
CONNECTED

(I) >>> 1520919571: Scheduled AWS connection checker
CONNECTED

*****  Turned WIFI ON at this point

(I) >>> 1520919586: Scheduled AWS connection checker
CONNECTED

*****  Terminated the application

com.amazonaws.services.iot.client.AWSIotException: Client is currently disconnecting (32102)
	at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnection.closeConnection(AwsIotMqttConnection.java:77)
	at com.amazonaws.services.iot.client.core.AwsIotConnection.disconnect(AwsIotConnection.java:263)
	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.disconnect(AbstractAwsIotClient.java:130)
	at com.amazonaws.services.iot.client.AWSIotMqttClient.disconnect(AWSIotMqttClient.java:557)
	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.disconnect(AbstractAwsIotClient.java:125)
	at com.amazonaws.services.iot.client.AWSIotMqttClient.disconnect(AWSIotMqttClient.java:536)
	at com.innodron.awsclient.MainAppController.shutdown(MainAppController.java:227)
	at com.innodron.awsclient.Main.lambda$0(Main.java:27)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:88)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:122)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$422(GlassWindowEventHandler.java:151)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:149)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1270)
	at com.sun.glass.ui.Window.notifyClose(Window.java:1174)
Caused by: Client is currently disconnecting (32102)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:455)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:632)
	at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnection.closeConnection(AwsIotMqttConnection.java:75)
	... 25 more
```

**Comment by liuszeng** [comment]
Hi @innodron ,

The SDK (Paho) should automatically handle reconnect upon MQTT connection loss for you. Is there any special reason you are performing connect by yourself in your application?

That being said, without the capability of accessing the physical layer, the SDK will not be able to know at the exactly time point when the cable is unplugged. The SDK reconnect logic is triggered whenever the underneath Paho notifies a client connection lost. More details can be found in the following links:
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java/src/main/java/com/amazonaws/services/iot/client/mqtt/AwsIotMqttConnection.java#L64
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java/src/main/java/com/amazonaws/services/iot/client/mqtt/AwsIotMqttClientListener.java#L39
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java/src/main/java/com/amazonaws/services/iot/client/core/AwsIotConnection.java#L369

One possible thing to make the connection loss detection more timely is to decrease the keep-alive interval configuration of the SDK client. A shorter keep-alive means more frequent MQTT pings and a higher chance to detect a network loss early.

Thanks,
Liusu
