### ISSUE TITLE
Missing possibility to get details about cause of connection failure

### ISSUE THREAD

**Issue by maciejdzikowicki** [aws/aws-iot-device-sdk-java#63]
Right now there is no way of getting root cause of connection failure. If I for example remove device certificate from IoT console, then I'm getting this in logs (which is expected):

```
08:51:53,322] <MQTT Con: 154801b3-6a43-43b5-9f16-2f6cf8d5e637> WARN  AwsIotMqttConnectionListener - Connect request failure
MqttException (0) - javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:715)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2011)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1113)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:108)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701)
	... 7 more
```
The only place where root cause is available is `AwsIotMqttConnectionListener.onFailure` but exception is not exposed. 

Could you add possibility to provide own implementation of `AwsIotMqttConnectionListener` or add root cause exception to some callback?

**Comment by maciejdzikowicki** [comment]
I would like to attach some callback/handler for specific exception types (for example `certificate_unknown` is a sign that device has been removed from IoT).

Right now there is no way to distinguish if device has issues with connection or has been removed.

**Comment by liuszeng** [comment]
Hi @maciejdzikowicki ,

Sorry for the delay.

After reading through the code base, it seems to me that a better way for the SDK to expose this is to allow customized configuration for connection listener, rather than modifying the existing callback function signatures. I have added an internal tracker for this. Appreciate your input on this.

Thanks,
Liusu

**Comment by maciejdzikowicki** [comment]
@liuszeng Thanks for feedback. It's maybe not critical feature, but would be very useful for our project.
