### ISSUE TITLE
MqttException (0) - java.io.IOException: Already connected

### ISSUE THREAD

**Issue by mpanicker** [aws/aws-iot-device-sdk-java#67]
I copied the accessKey, secret and session(into properties file aws-iot-sdk-samples.properties)  from a different program that authenticates using username, password against a Cognito user pool and then using the returned JWT to get a Federated Identity and then got the temporary credentials for that Identity.
When I execute awsIotClient.connect(); in the main program I get 
WARNING: Connect request failure
MqttException (0) - java.io.IOException: Already connected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Already connected
	at java.io.PipedOutputStream.connect(PipedOutputStream.java:100)
	at java.io.PipedInputStream.connect(PipedInputStream.java:188)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.<init>(WebSocketReceiver.java:42)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:78)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	... 1 more

Any help will be appreciated

**Comment by shibinvadayatt** [comment]
Please refer: https://stackoverflow.com/questions/44244375/aws-iot-android-application-over-mqtt-throws-mqttexception-0-java-io-ioexcep

If anybody still needs help, please reach me over mail: shibinfrancis@live.com or over facebook( www.facebook.com/shibinvadayatt )

BR/Francis Shibin

**Comment by anuragdce** [comment]
@shibinvadayatt I am also facing the similar issue and i also did integrate the same logic as provided in the forum but still i am getting the same error

Please check the code below and please provide your feedback

 private Flowable<Boolean> connect(String token) {
    return Flowable.create(e -> {
      Map<String, String> logins = new HashMap<>();
      logins.put("cognito-idp." + REGION.getName() + ".amazonaws.com/" + USER_POOL_ID, token);
      credentialsProvider.setLogins(logins);


      AttachPolicyRequest attachPolicyReq = new AttachPolicyRequest();
      attachPolicyReq.setPolicyName("iot-connected-car"); // name of your IOT AWS policy
      attachPolicyReq.setTarget(credentialsProvider.getIdentityPoolId());

      AWSIotClient mIotAndroidClient = new AWSIotClient(credentialsProvider);
      mIotAndroidClient.setRegion(Region.getRegion(REGION)); // name of your IoT Region such as "us-east-1"
      mIotAndroidClient.attachPolicy(attachPolicyReq);

      /*AmazonCognitoIdentity cognitoIdentity = new AmazonCognitoIdentityClient(credentialsProvider);
      GetIdRequest getIdReq = new GetIdRequest();
      getIdReq.setLogins(logins); //or if you have already set provider logins just use credentialsProvider.getLogins()
      getIdReq.setIdentityPoolId(credentialsProvider.getIdentityPoolId());
      GetIdResult getIdRes = cognitoIdentity.getId(getIdReq);

      AttachPrincipalPolicyRequest attachPolicyReq = new AttachPrincipalPolicyRequest(); //in docs it called AttachPolicyRequest but it`s wrong
      attachPolicyReq.setPolicyName("iot-connected-car"); //name of your IOTAWS policy
      attachPolicyReq.setPrincipal(getIdRes.getIdentityId());
      new AWSIotClient(credentialsProvider).attachPrincipalPolicy(attachPolicyReq);*/

      String uuid = UUID.randomUUID().toString();

      mqttManager = new AWSIotMqttManager(uuid, IOT_ENDPOINT);
      mqttManager.connect(credentialsProvider, (status, throwable) -> {

        if (throwable != null) {
          e.onNext(false);
        } else {
          e.onNext(true);
        }
      });

      e.setCancellable(() -> {
        if (mqttManager != null) {
          mqttManager.disconnect();
        }
      });

    }, BackpressureStrategy.LATEST);
  }

thanks

**Comment by aniket91** [comment]
I was getting the same error but in my case, the issue was that the authenticated role corresponding to the identity pool did not have required permissions. It does not make sense to me - why would SDK throw "already connected" error if there are permission issues. This should be fixed by the AWS team. 

I have tried to summarize it in the SO question - https://stackoverflow.com/a/54898307/2396539. Hoping it helps people stuck in a similar situation.

**Comment by kirantpatil** [comment]
Hello, 

We are facing [this](https://github.com/aws-amplify/aws-sdk-android/issues/1812) issue.

Could you please help us to figure out the root cause of the issue ?

Thanks.

**Comment by shibinvadayatt** [comment]
https://stackoverflow.com/questions/44244375/aws-iot-android-application-over-mqtt-throws-mqttexception-0-java-io-ioexcep

**Comment by AngelHadzhiev** [comment]
Hey, 
I experience the same issue now. I tried some proposed solution I found in this thread but nothing really helped. 
Is there any new information on this problem? How can I resolve it?

**Comment by gsimard** [comment]
I am facing the same problem. You should re-open this issue.

**Comment by gsimard** [comment]
In my case, I had to get the provided identityId from Cognito and forward it to AWSIotMqttManager's constructor.

```
val credentialsProvider = CognitoCachingCredentialsProvider(
    applicationContext,
    POOL_ID, // Cognito Identity Pool ID
    Regions.CA_CENTRAL_1
)

val uniqueClientId = credentialsProvider.identityId

// Initialize the MQTT manager with the unique client ID
mqttManager = AWSIotMqttManager(uniqueClientId, ENDPOINT)
```

**Comment by jmklix** [comment]
Please open a new issue if you are still running into this exception and provide as much detail as possible. I would also recommend checking out our [v2 java sdk](https://github.com/aws/aws-iot-device-sdk-java-v2)

**Comment by bretambrose** [comment]
You appear to be using an unrelated library (Amplify).  This is not the Amplify repo and the AWSIotMqttManager type does not exist here.  

You can find it here though: https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L687
