### ISSUE TITLE
AWS SDK is disconnected and not able to reconnect

### ISSUE THREAD

**Issue by maciejdzikowicki** [aws/aws-iot-device-sdk-java#70]
Hello
We are using aws sdk in java in order to connect to IoT from our devices. 
Right now we have issue that SDK report connection state as `CONNECTED` (`AWSIotMqttClient.getConnectionStatus() == AWSIotConnectionStatus.CONNECTED`), but device is disconnected and is not trying to reconnected as usual. 

When we check connection from shell, we see this:
```
java      23768                  unifi  156u     IPv6     649024       0t0        TCP 192.168.1.183:38757->ec2-52-33-190-207.us-west-2.compute.amazonaws.com:8883 (CLOSE_WAIT)
```

Device lost it's connectivity and is not able to recover. Please let us know how should we handle this case?

Below are logs:
```
[2018-07-06 01:12:51,411] <MQTT Ping: 0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04> ERROR ClientState - 0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04: Timed out as no write activity, keepAlive=30,000 lastOutboundActivity=1,530,864,691,404 la
stInboundActivity=1,530,864,661,474 time=1,530,864,771,401 lastPing=0
[2018-07-06 01:12:51,413] <MQTT Ping: 0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04> WARN  AwsIotMqttMessageListener - Request failed for topic $aws/things/0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04/shadow/update: Timed out while waiting t
o write messages to the server (32002)
[2018-07-06 01:12:51,420] <pool-5-thread-1> WARN  AwsIotDeviceReportMessage - Failed to publish device report: null
[2018-07-06 01:12:51,420] <pool-5-thread-1> INFO  AwsIotConnection - Connection temporarily lost
[2018-07-06 01:12:51,421] <pool-5-thread-1> INFO  AbstractAwsIotClient - Client connection lost: 0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04
[2018-07-06 01:12:51,422] <pool-5-thread-1> WARN  AwsIotDeviceCommandManager - Request was cancelled: UPDATE/ccf791dc-9363-4372-a956-57085239901e
[2018-07-06 01:12:54,421] <pool-5-thread-1> INFO  AwsIotConnection - Connection is being retried
[2018-07-06 01:13:23,175] <webrtc-connection> DEBUG webrtc - active webrtc sessions: 0
[2018-07-06 01:13:32,593] <pool-5-thread-1> INFO  AwsIotConnection - Connection successfully established
[2018-07-06 01:13:32,599] <pool-5-thread-1> INFO  AbstractAwsIotClient - Client connection active: 0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04
[2018-07-06 01:13:32,851] <pool-5-thread-1> WARN  AwsIotDeviceCommandManager - Unknown command received from topic $aws/things/0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04/shadow/update/accepted
[2018-07-06 01:13:32,956] <pool-5-thread-1> INFO  sdn    - {"payload":{},"requestId":"c072402c-70eb-4da2-9a2f-1eced874dbc4","session_identifier":{"id":null,"session_type":"sso"},"cmd":"sync-access"}
[2018-07-06 01:13:32,961] <pool-5-thread-1> INFO  sdn    - sync admin access
[2018-07-06 01:13:37,685] <pool-5-thread-1> INFO  AwsIotDeviceSyncMessage - Received shadow version number: 160816
[2018-07-06 01:14:23,175] <webrtc-connection> DEBUG webrtc - active webrtc sessions: 0
[2018-07-06 01:14:31,483] <pool-5-thread-1> WARN  AwsIotDeviceCommandManager - Unknown command received from topic $aws/things/0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04/shadow/update/accepted
[2018-07-06 01:14:31,533] <pool-5-thread-1> WARN  AwsIotDeviceCommandManager - Unknown command received from topic $aws/things/0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04/shadow/update/rejected
[2018-07-06 01:14:32,684] <pool-5-thread-1> WARN  AwsIotDeviceReportMessage - Device version conflict, restart version synchronization
[2018-07-06 01:14:32,762] <pool-5-thread-1> INFO  AwsIotDeviceSyncMessage - Received shadow version number: 160825
[2018-07-06 01:15:23,372] <webrtc-connection> DEBUG webrtc - active webrtc sessions: 0
[2018-07-06 01:15:26,320] <pool-5-thread-1> INFO  AwsIotConnection - Connection temporarily lost
[2018-07-06 01:15:26,324] <pool-5-thread-1> INFO  AbstractAwsIotClient - Client connection lost: 0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04
[2018-07-06 01:15:29,324] <pool-5-thread-1> INFO  AwsIotConnection - Connection is being retried
[2018-07-06 01:15:30,487] <pool-5-thread-1> INFO  AwsIotConnection - Connection successfully established
[2018-07-06 01:15:30,515] <pool-5-thread-1> WARN  AwsIotConnection - Failed to send queued messages, will disconnect
com.amazonaws.services.iot.client.AWSIotException: Client is currently disconnecting (32102)
        at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnection.unsubscribeTopic(AwsIotMqttConnection.java:118)
        at com.amazonaws.services.iot.client.core.AwsIotConnection.onConnectionSuccess(AwsIotConnection.java:286)
        at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener$1.run(AwsIotMqttConnectionListener.java:52)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: Client is currently disconnecting (32102)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:372)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:181)
        ... 7 more
[2018-07-06 01:15:30,547] <pool-5-thread-1> WARN  AwsIotConnection - Failed to disconnect
com.amazonaws.services.iot.client.AWSIotException: Client is disconnected (32101)
    at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnection.closeConnection(AwsIotMqttConnection.java:77)
    at com.amazonaws.services.iot.client.core.AwsIotConnection.onConnectionSuccess(AwsIotConnection.java:297)
    at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener$1.run(AwsIotMqttConnectionListener.java:52)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: Client is disconnected (32101)
    at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
    at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:489)
    at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:826)
    at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnection.closeConnection(AwsIotMqttConnection.java:75)
    ... 9 more
[2018-07-06 01:15:30,550] <pool-5-thread-1> INFO  AbstractAwsIotClient - Client connection active: 0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04
[2018-07-06 01:15:33,563] <pool-5-thread-1> WARN  AwsIotDeviceDeltaListener - Timeout when subscribing to device topic $aws/things/0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04/shadow/update/delta
[2018-07-06 01:15:33,565] <pool-5-thread-1> WARN  AwsIotDeviceCommandAckListener - Timeout when subscribing to device topic $aws/things/0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04/shadow/get/accepted
[2018-07-06 01:15:33,566] <pool-5-thread-1> WARN  AwsIotDeviceCommandAckListener - Timeout when subscribing to device topic $aws/things/0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04/shadow/get/rejected
[2018-07-06 01:15:33,567] <pool-5-thread-1> WARN  AwsIotDeviceCommandAckListener - Timeout when subscribing to device topic $aws/things/0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04/shadow/update/accepted
[2018-07-06 01:15:33,568] <pool-5-thread-1> WARN  AwsIotDeviceCommandAckListener - Timeout when subscribing to device topic $aws/things/0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04/shadow/update/rejected
[2018-07-06 01:15:33,568] <pool-5-thread-1> WARN  AwsIotDeviceCommandAckListener - Timeout when subscribing to device topic $aws/things/0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04/shadow/delete/accepted
[2018-07-06 01:15:33,569] <pool-5-thread-1> WARN  AwsIotDeviceCommandAckListener - Timeout when subscribing to device topic $aws/things/0418D6A00D7300000000016ECAE300000000017C22300000000055E66B04/shadow/delete/rejected
```

**Comment by maciejdzikowicki** [comment]
It looks like it was caused by paho in version 1.2.0
