### ISSUE TITLE
issue in running PublishSubscribeSample example

### ISSUE THREAD

**Issue by subodh007** [aws/aws-iot-device-sdk-java#78]
I have provided following details:-

        String clientEndpoint = arguments.getNotNull("clientEndpoint", "xxxxxxx-xxx.iot.us-east-1.amazonaws.com");
        String clientId = arguments.getNotNull("clientId", "mq101");

        String certificateFile = arguments.get("certificateFile", "asdads-certificate.pem.crt");
        String privateKeyFile = arguments.get("privateKeyFile", "asdasd-private.pem.key");

and getting following error while connecting to thing

Nov 19, 2018 7:28:38 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
Unable to connect to server (32103) - java.net.ConnectException: Connection timed out: connect
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
	... 3 more

Nov 19, 2018 7:28:38 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Nov 19, 2018 7:28:38 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: mq101
Nov 19, 2018 7:28:42 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried

**Comment by sapher** [comment]
The code you have posted is not enough to help you :°
